version: '3.3'
services:
  nginx-official:
    depends_on:
      - wordpress-official
    image: nginx:1.10.3-alpine
    ports:
      - '${WP_PORT}:80'
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
      - ${WP_WWW}:/var/www
      - ${WP_PUBLIC}:/var/www/html
  wordpress-official:
    networks:
      - default
      - wp-docker-compose_wordpress-net
    build: ./docker
    volumes:
      - ./config/php.conf.error.ini:/usr/local/etc/php/conf.d/error.ini
      - ./config/php.conf.mail.ini:/usr/local/etc/php/conf.d/mail.ini
      - ./config/msmtprc:/etc/msmtprc
      - ${WP_WWW}:/var/www
      - ${WP_PUBLIC}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
networks:
  wp-docker-compose_wordpress-net:
    external: true
